In [1]:
import pandas as pd
import numpy as np

Question 1:
What's the version of Pandas that you installed?

In [2]:
pd.__version__

'2.0.3'

Question 2:
How many columns are in the dataset?

In [3]:
housing = pd.read_csv('raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv')

In [4]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [5]:
housing.shape

(20640, 10)

Question 3
Which columns in the dataset have missing values?

In [6]:
housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Question 4
How many unique values does the ocean_proximity column have?


In [7]:
housing.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

Question 5:
What's the average value of the median_house_value for the houses located near the bay?

In [8]:
housing.groupby("ocean_proximity").median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

Question 6:\
Calculate the average of total_bedrooms column in the dataset.\
Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.\
Now, calculate the average of total_bedrooms again.\
Has it changed?

In [9]:
housing['total_bedrooms'].mean()

537.8705525375618

In [10]:
men = housing['total_bedrooms'].mean()


In [11]:
housing['total_bedrooms'].fillna(men)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [12]:
housing['total_bedrooms'].nunique()

1923

In [13]:
housing['total_bedrooms'].isnull().sum()

207

In [14]:
housing['total_bedrooms'].fillna(men)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [15]:
housing['total_bedrooms'].mean()

537.8705525375618

Select all the options located on islands.\
Select only columns housing_median_age, total_rooms, total_bedrooms.\
Get the underlying NumPy array. Let's call it X.\
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.\
Compute the inverse of XTX.\
Create an array y with values [950, 1300, 800, 1000, 1300].\
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.\
What's the value of the last element of w?

In [16]:
island = housing[housing['ocean_proximity'] == 'ISLAND']
island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [17]:
isl = island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
isl

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [18]:
X= isl.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [19]:
XT = np.transpose(X)
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [20]:
XTX = np.dot(X, XT)
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [21]:
Y = np.array([950, 1300, 800, 1000, 1300])
Y

array([ 950, 1300,  800, 1000, 1300])

In [22]:
I = np.linalg.inv(XTX) 
I

array([[ 4.50889141e+08, -2.65092831e+09,  2.66146909e+09,
        -5.26157398e+08,  5.04760603e+08],
       [ 2.60444475e+11, -8.57212683e+10, -2.18771394e+10,
         5.28097320e+11, -9.96480838e+11],
       [-2.81125831e+11,  9.36268739e+10,  2.24292933e+10,
        -5.69400064e+11,  1.07463035e+12],
       [ 1.50907516e+11, -5.52172767e+10, -6.69134384e+09,
         3.02798151e+11, -5.72439948e+11],
       [-2.33928769e+11,  8.73028262e+10,  8.53028316e+09,
        -4.68398445e+11,  8.85843939e+11]])

In [23]:
w = np.dot(XTX, I) * Y
w

array([[-6.23743652e+04,  1.00278885e+04, -1.00701523e+03,
         3.75740967e+04, -5.40626868e+05],
       [-3.81948242e+04, -3.06794525e+04,  2.15956573e+03,
         7.90368652e+04, -1.83575806e+05],
       [ 3.38214844e+04, -2.83570435e+04,  7.70438843e+03,
        -1.56799805e+05, -7.30040137e+05],
       [ 3.22072266e+04, -1.44332214e+04,  2.08900452e+03,
         1.30362793e+05, -3.25539551e+04],
       [-2.11718262e+04, -2.07511826e+04, -5.55388641e+02,
        -3.78795166e+04, -2.35093384e+04]])